CREATE TABLE UserSoporte(
IdUser INT NOT NULL IDENTITY(1,1) PRIMARY KEY,
Nombre VARCHAR(20) NOT NULL,
Apellido VARCHAR(20) NOT NULL,
Usuario VARCHAR(20) NOT NULL,
Pasword VARCHAR(15) NOT NULL
);

CREATE TABLE LogsContabilidadSoporte(
IdLog	 INT NOT NULL IDENTITY(1,1) PRIMARY KEY,
Fecha datetime NOT NULL,
Componente	VARCHAR(20) NOT NULL,
Tipo	VARCHAR(40) NOT NULL,
Mensaje	VARCHAR(MAX) NOT NULL,
Origen INT NOT NULL,
IdUser INT NULL
);

CREATE TABLE ProyectosSoporte(
IdProyecto INT NOT NULL IDENTITY(1,1) PRIMARY KEY,
Proyecto VARCHAR(30) NOT NULL,
Imagen VARCHAR(100),
urlComponente VARCHAR(40) NOT NULL
);